import Head from "next/head";
import { useState } from "react";
import Link from "next/link";
import Header from "../components/header";
import styles from "../styles/Home.module.css";

const faqData = [
  {
    question: "What is GAINS and who is it for?",
    answer: "GAINS (Generate, Analyze, Interpret, Navigate, Share) is a web-based platform designed specifically for CSC 230 Software Design students. It helps students learn statistical analysis and R programming through an intuitive three-step workflow that generates professional R code without requiring prior R experience."
  },
  {
    question: "How does the 3-step workflow work?",
    answer: "The workflow is simple: 1) Upload your dataset (CSV file) or enter data manually, 2) Select an R tool from our collection (linear regression, bar charts, line charts, etc.), and 3) Copy or download the generated R code to use in RStudio. Each step is designed to be beginner-friendly while producing professional results."
  },
  {
    question: "What file formats are supported for data upload?",
    answer: "Currently, GAINS supports CSV (Comma-Separated Values) files for data upload. The platform automatically parses your CSV file and validates the data to ensure it's ready for analysis. You can also manually enter data points directly into the platform if you prefer."
  },
  {
    question: "What R tools are available on the platform?",
    answer: "GAINS offers a comprehensive collection of R statistical tools including Linear Regression with diagnostic plots, Bar Charts for categorical data visualization, Line Charts for time series analysis, Scatter Plots for correlation analysis, and various statistical tests. More tools are being added regularly."
  },
  {
    question: "Do I need to know R programming to use GAINS?",
    answer: "No prior R programming experience is required! GAINS is designed for beginners and generates clean, well-commented R code that you can copy directly into RStudio. The platform handles all the complex R syntax while you focus on understanding the statistical concepts."
  },
  {
    question: "How do I use the generated R code in RStudio?",
    answer: "Simply copy the generated R code from GAINS and paste it into RStudio. The code includes all necessary libraries, data setup, and analysis commands. You can run the entire script at once or execute it line by line to understand each step of the analysis."
  },
  {
    question: "Can I edit the generated R code?",
    answer: "Yes! While GAINS generates complete, ready-to-run R code, you can modify it in RStudio to customize your analysis. The generated code is well-commented and follows R best practices, making it easy to understand and modify for your specific needs."
  },
  {
    question: "Is my data stored on the platform?",
    answer: "GAINS processes your data in real-time for analysis and code generation. We do not permanently store your datasets on our servers. Your data remains private and is only used to generate the appropriate R code for your analysis."
  },
  {
    question: "What if I encounter errors with the generated R code?",
    answer: "The R code generated by GAINS is tested and validated, but if you encounter issues, check that you have the required R packages installed. The code includes library loading commands, but you may need to install packages like 'ggplot2', 'dplyr', or others if they're not already installed in your R environment."
  },
  {
    question: "Can I use GAINS for my CSC 230 assignments?",
    answer: "Absolutely! GAINS is specifically designed to support CSC 230 coursework. It helps you understand statistical concepts while generating professional R code that you can use for assignments, projects, and learning exercises. The platform is a great tool for exploring different statistical methods and visualizations."
  },
  {
    question: "Who developed GAINS?",
    answer: "GAINS was developed as a collaborative project by CSC 230 students: Yaroslav, Jonathan, Aiden, Kevin, Murat, and Braden. It was created as part of the Software Design and Engineering course to help fellow students learn statistical analysis and R programming."
  },
  {
    question: "Is GAINS free to use?",
    answer: "Yes, GAINS is completely free to use for CSC 230 students and anyone interested in learning statistical analysis. There are no subscription fees, usage limits, or hidden costs. The platform is designed to be accessible and educational."
  }
];

export default function FAQ() {
  const [openItems, setOpenItems] = useState({});

  const toggleItem = (index) => {
    setOpenItems(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  return (
    <>
      <Head>
        <title>FAQ - GAINS Platform</title>
        <meta name="description" content="Frequently asked questions about GAINS statistical analysis platform" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        <Header />
        <main className={styles.homeMain}>
          {/* FAQ Section */}
          <section className={styles.featuresSection}>
            <div className={styles.sectionHeaderRow}>
              <h2 className={styles.sectionTitle}>Frequently Asked Questions</h2>
              <p className={styles.sectionSubtitle}>
                Find answers to common questions about using GAINS for statistical analysis and R code generation.
              </p>
            </div>
            
            <div className={styles.faqContainer}>
              {faqData.map((item, index) => (
                <div key={index} className={styles.faqItem}>
                  <button 
                    className={styles.faqQuestion}
                    onClick={() => toggleItem(index)}
                    aria-expanded={openItems[index]}
                  >
                    <span className={styles.faqQuestionText}>{item.question}</span>
                    <span className={`${styles.faqIcon} ${openItems[index] ? styles.faqIconOpen : ''}`}>
                      +
                    </span>
                  </button>
                  <div className={`${styles.faqAnswer} ${openItems[index] ? styles.faqAnswerOpen : ''}`}>
                    <p>{item.answer}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* CTA Section */}
          <section className={styles.ctaSection}>
            <div>
              <h2 className={styles.sectionTitle}>Still have questions?</h2>
              <p className={styles.sectionSubtitle}>
                If you can't find the answer you're looking for, try exploring the platform or contact your CSC 230 instructor for additional support.
              </p>
            </div>
            <div className={styles.ctaActions}>
              <Link href="/linear-regression" className={styles.primaryButton}>
                Try GAINS Now
              </Link>
              <Link href="/about" className={styles.secondaryButton}>
                Learn More
              </Link>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
